GET http://localhost:3333/videos?localhost:3333/videos

###

POST http://localhost:3333/videos
Content-Type: application/json

{
    "title":"Video 01",
    "description":"Bruh",
    "duration":180
}

###
PUT http://localhost:3333/videos/8c8115ad-c4ed-499d-8e49-7dc1cb5a98d0
Content-Type: application/json

{
    "title":"Video #001",
    "description":"Brother",
    "duration":180
}

###

DELETE http://localhost:3333/videos/1d0585a3-52e9-4bc5-b9b3-1778cb5cb030