GET https://makingthings.onrender.com/videos

###

POST https://makingthings.onrender.com/videos
Content-Type: application/json

{
    "title":"Video 01",
    "description":"Bruh",
    "duration":180
}

###
PUT https://makingthings.onrender.com/videos/8c8115ad-c4ed-499d-8e49-7dc1cb5a98d0
Content-Type: application/json

{
    "title":"Video #001",
    "description":"Maysa é uma Bebe da Mamãe",
    "duration":180
}

###

DELETE https://makingthings.onrender.com/videos